#!/bin/bash

function usage() {
	echo "usage: app start|stop|update"
}

if [ "$#" -ne 1 ]; then
	usage
elif [ $1 = "start" ]; then
	cd ./server/
	npm start >/dev/null&
	cd ../client/
	npm start&
	cd ..
elif [ $1 = "stop" ]; then
	kill `pidof @angular/cli`; kill `pidof node`
elif [ $1 = "update" ]; then
	cd ./server/
	npm install&
	cd ../client/
	npm install&
	cd ..
else
	usage 
fi

